### ISSUE TITLE
配置文件问题

### ISSUE THREAD

**Issue by yangdaCheny** [wyx2685/V2bX#10]
"RouteConfigPath": "/etc/V2bX/route.json",
"OutBoundConfigPath": "/etc/V2bX/custom_outbound.json",
你好，我想做二级路由，这两个参数应该放在配置文件哪一层下边
![image](https://github.com/user-attachments/assets/c436e72b-e069-40f8-b55d-f7682eaf16ce)

**Comment by wyx2685** [comment]
@yangdaCheny 麻烦用脚本装，要用这两个文件你选xray核

**Comment by yangdaCheny** [comment]
我用的是一键安装的那个命令，那个已经安装好了可以用吗？然后hy2协议的可以转发吗

「wyx2685 ***@***.***>」在 2024年7月16日 週二，07:42 寫道：

**Comment by wyx2685** [comment]
@yangdaCheny 麻烦看文档吧，提问进群问，这里不是提问的地方
