### ISSUE TITLE
0.0.9对接xb不能连，日志卡在了这里

### ISSUE THREAD

**Issue by JusufUs** [wyx2685/V2bX#11]
请输入选择 [0-17]: 8
-- Journal begins at Sun 2024-04-28 23:29:09 HKT. --
Jul 17 16:33:05 debian systemd[1]: Started V2bX Service.
Jul 17 16:33:05 debian V2bX[5784]:  
Jul 17 16:33:05 debian V2bX[5784]:   _/      _/    _/_/    _/        _/      _/
Jul 17 16:33:05 debian V2bX[5784]:  _/      _/  _/    _/  _/_/_/      _/  _/
Jul 17 16:33:05 debian V2bX[5784]: _/      _/      _/    _/    _/      _/
Jul 17 16:33:05 debian V2bX[5784]:  _/  _/      _/      _/    _/    _/  _/
Jul 17 16:33:05 debian V2bX[5784]:   _/      _/_/_/_/  _/_/_/    _/      _/
Jul 17 16:33:05 debian V2bX[5784]:                                                 
Jul 17 16:33:05 debian V2bX[5784]: V2bX v0.0.9-20240715 (A V2board backend based on multi core)

hy2，日志卡在这里不动了，从后端curl主站是通的

Jul 17 17:30:43 debian V2bX[5784]: 2024-07-17T17:30:43+08:00        ERROR        Server Error        {"error": "quic: server closed"}

选6，重启节点后查看日志有一条这样的错误，然后又卡在了上面的日志那里

**Comment by fanqing972** [comment]
我也是遇到这个问题
V2bX[915934]: +0800 2024-07-17 17:16:55 ERROR router: failed to initialize geosite: read geosite: code google not exists!
Stopping V2bX Service...
V2bX.service: Succeeded.
Stopped V2bX Service.
Started V2bX Service.                                           
V2bX v0.0.9-20240715 (A V2board backend based on multi core)
怎么能解决

**Comment by JusufUs** [comment]
> 我也是遇到这个问题 V2bX[915934]: +0800 2024-07-17 17:16:55 ERROR router: failed to initialize geosite: read geosite: code google not exists! Stopping V2bX Service... V2bX.service: Succeeded. Stopped V2bX Service. Started V2bX Service. V2bX v0.0.9-20240715 (A V2board backend based on multi core) 怎么能解决

你的和我这个不一样，你的已经标明了错误原因，改下路由文件就行了
V2bX[915934]: +0800 2024-07-17 17:16:55 ERROR router: failed to initialize geosite: read geosite: code google not exists!

**Comment by fanqing972** [comment]
> > 我也是遇到这个问题 V2bX[915934]: +0800 2024-07-17 17:16:55 ERROR router: failed to initialize geosite: read geosite: code google not exists! Stopping V2bX Service... V2bX.service: Succeeded. Stopped V2bX Service. Started V2bX Service. V2bX v0.0.9-20240715 (A V2board backend based on multi core) 怎么能解决
> 
> 你的和我这个不一样，你的已经标明了错误原因，改下路由文件就行了 V2bX[915934]: +0800 2024-07-17 17:16:55 ERROR router: failed to initialize geosite: read geosite: code google not exists!

我这个是前面的，后来检查路由，改了也一样没用。就连卸载重装也一样无济于事。

**Comment by wyx2685** [comment]
> 请输入选择 [0-17]: 8
> -- Journal begins at Sun 2024-04-28 23:29:09 HKT. --
> Jul 17 16:33:05 debian systemd[1]: Started V2bX Service.
> Jul 17 16:33:05 debian V2bX[5784]:  
> Jul 17 16:33:05 debian V2bX[5784]:   _/      _/    _/_/    _/        _/      _/
> Jul 17 16:33:05 debian V2bX[5784]:  _/      _/  _/    _/  _/_/_/      _/  _/
> Jul 17 16:33:05 debian V2bX[5784]: _/      _/      _/    _/    _/      _/
> Jul 17 16:33:05 debian V2bX[5784]:  _/  _/      _/      _/    _/    _/  _/
> Jul 17 16:33:05 debian V2bX[5784]:   _/      _/_/_/_/  _/_/_/    _/      _/
> Jul 17 16:33:05 debian V2bX[5784]:                                                 
> Jul 17 16:33:05 debian V2bX[5784]: V2bX v0.0.9-20240715 (A V2board backend based on multi core)
> 
> hy2，日志卡在这里不动了，从后端curl主站是通的
> 
> 
> Jul 17 17:30:43 debian V2bX[5784]: 2024-07-17T17:30:43+08:00        ERROR        Server Error        {"error": "quic: server closed"}
> 
> 选6，重启节点后查看日志有一条这样的错误，然后又卡在了上面的日志那里


没有显示就是正常启动吧，日志等级不够高看不到而已

**Comment by tristesky** [comment]
这个脚本的审计规则在哪个位置呢

**Comment by vlesstop** [comment]
@tristesky 在安装文件夹内。

**Comment by tristesky** [comment]
> @tristesky 在安装文件夹内。

谢谢大佬
