### ISSUE TITLE
用户数量限制功能似乎无法正常工作

### ISSUE THREAD

**Issue by shiritoshiro** [wyx2685/V2bX#13]
**描述该错误**
根据文档https://v2bx.v-50.me/v2bx/v2bx-pei-zhi-wen-jian-shuo-ming/config添加了限制器相关配置,发现IPLimit似乎没有效果，ConnLimit则会有奇怪的问题，例如谷歌能打开，但是youtube上不去等，或者谷歌一会儿打得开一会儿打不开

根据文档描述，IPLimit为用户ip限制，ConnLimit为用户连接数量限制，现发现ip数量限制貌似无效，用户连接数量限制无法限制客户端数量，限制的好像是tcp连接数量？

{
            "Core": "xray",
            "ApiHost": "http://xxxxxx"
            "ApiKey": "xxxx",
            "NodeID": 1,
            "NodeType": "vless",
            "Timeout": 30,
            "ListenIP": "0.0.0.0",
            "SendIP": "0.0.0.0",
            "DeviceOnlineMinTraffic": 10,
            "EnableProxyProtocol": false,
            "EnableUot": true,
            "EnableTFO": true,
            "DNSType": "UseIPv4",
            "LimitConfig":{
                "EnableRealtime":true,
                "ConnLimit":1,
                "IPLimit":1
            },
            "CertConfig": {
                "CertMode": "none",
                "RejectUnknownSni": false,
                "CertDomain": "example.com",
                "CertFile": "/etc/V2bX/fullchain.cer",
                "KeyFile": "/etc/V2bX/cert.key",
                "Email": "v2bx@github.com",
                "Provider": "cloudflare",
                "DNSEnv": {
                    "EnvName": "env1"
                }
            }
        },

**环境和版本**
 - 系统 ubuntu2404
 - 架构 amd64
 - 面板 xboard
 - 协议 vlexx
 - 版本 V2bX v0.0.9-20240717
 - 部署方式 [例如：一键脚本]

**Comment by wyx2685** [comment]
@shiritoshiro 没用过 原版未完成功能 以后会剔除
