### ISSUE TITLE
node status report stops

### ISSUE THREAD

**Issue by omident** [wyx2685/V2bX#15]
**描述该错误**

server could not report online users to V2board. node gets yellow in v2board. although it's config would connect!
**复现**
it think this bug heppens when more than 150 users are connected

**环境和版本**
 - 系统 [例如：Ubuntu 22]
 - 架构 [例如：AMD64]
 - 面板 [例如：V2board]
 - 协议 [例如：hysteria]
 - 版本 [例如：0.0.11]
 - 部署方式 [例如：一键脚本]

![image](https://github.com/user-attachments/assets/fe9dfc22-3126-46b7-b729-86ee49ccbdab)

**Comment by wyx2685** [comment]
it was fixed in last commit
just wait new version release
