### ISSUE TITLE
V2BX自行生成的SSL证书不能用于银行应用

### ISSUE THREAD

**Issue by dziiofficialo0** [wyx2685/V2bX#16]
**描述该错误**
V2BX自行生成的SSL证书不能用于银行应用

**复现**
复现该bug的步骤

**环境和版本**
 - 系统 [例如：Debian 11]
 - 架构 [例如：AMD64]
 - 面板 [例如：V2board]
 - 协议 [例如：vmess]
 - 版本 [例如：0.8.2.2]
 - 部署方式 [例如：一键脚本]

**日志和错误**
请使用`xrayr log`查看并添加日志，以帮助解释你的问题

**额外的内容**
我无法使用银行应用程序或政府应用程序，因为提供的 SSL 证书无效。您能指导我如何手动添加 SSL 证书吗？我非常感谢你

**Comment by wyx2685** [comment]
@dziiofficialo0 描述不足，这里也不负责银行应用的问题
