### ISSUE TITLE
新版本设置过程中，老是重启失败，用的面板是Xboard

### ISSUE THREAD

**Issue by willwongup** [wyx2685/V2bX#19]
新版本设置过程中，老是重启失败，用的面板是Xboard
time="2024-09-01T00:37:40Z" level=error msg="Run nodes failed" err="start node controller [https://www.****.top-vmess-40] error: failed to get user alive list: unmarshal user alive list error: invalid character '<' looking for beginning of value"

**Comment by wyx2685** [comment]
把你的cdn先关了
