### ISSUE TITLE
更新0.0.14后启动失败，面板Xboard #

### ISSUE THREAD

**Issue by Cd1s** [wyx2685/V2bX#20]
**启动出现如下错误，使用老版本的启动没有这项错误，已切换无CDN的域名**

`V2bX v0.0.14 (A V2board backend based on multi core)
Sep 02 10:17:51 79f805d1bb V2bX[13291]: time="2024-09-02T10:17:51Z" level=error msg="Run nodes failed" err="start node controller [https://xxx.me-shadowsocks-486] error: failed to get user alive list: unmarshal user alive list error: invalid character '<' looking for beginning of value"
Sep 02 10:17:51 79f805d1bb systemd[1]: V2bX.service: Succeeded.`

其他机器老版本正常，专门升级测试发现对接不上

**Comment by liujazz** [comment]
我也有同样的问题

**Comment by Cd1s** [comment]
V2bX log

> 我也有同样的问题

替换老版本 /usr/local/V2bX/V2bX，重启用着先

**Comment by wyx2685** [comment]
@Cd1s 没有做兼容，后面再改

**Comment by wyx2685** [comment]
https://github.com/wyx2685/V2bX/commit/7184e496505330b20676fee53a752cb5fbcc15ac

**Comment by Cd1s** [comment]
感谢修复
