### ISSUE TITLE
vless+tls+ws+xtls或vless+tls+tcp都不能用

### ISSUE THREAD

**Issue by Jungann-Z** [wyx2685/V2bX#24]
**描述该错误**
vless+tls+ws+xtls或vless+tls+tcp都不能用同台服务器搭建vmless能用 ，    换了一台独立的节点服务器   单独搭建vless也不能用

**复现**
复现该bug的步骤

**环境和版本**
 - 系统 [ubuntu]

 - 面板 [ Xboard ]
 - 协议 [例如：vless]
 - 部署方式 [例如：一键脚本]

**日志和错误**
请使用`xrayr log`查看并添加日志，以帮助解释你的问题

**额外的内容**
在这里添加关于问题的任何其他内容

**Comment by wyx2685** [comment]
缺少提问必要信息
