### ISSUE TITLE
请问hysteria 2协议可以看网页连接情况吗？

### ISSUE THREAD

**Issue by lowprofileusername** [wyx2685/V2bX#25]
**描述该错误**
简单地描述一下这个bug是什么

不知如何查看hystieria 2的连接情况

**复现**
请自行复现，并贴出详细步骤操作过程
hysteria 2协议时查看v2bx 日志无任何输出

**日志和错误**
请使用`v2bx log`查看并添加日志，没有日志的issue不会得到答复并且会被直接关闭

**额外的内容**
在这里添加关于问题的任何其他内容

**Comment by wyx2685** [comment]
改配置日志等级开debug
