### ISSUE TITLE
关于支付方式选择Epay易支付报错的问题

### ISSUE THREAD

**Issue by coomeng** [wyx2685/V2bX#26]
目前如果支付方式选择Epay，在支付的时候会默认为QQ钱包收款（目前我测试的是）

发现是易支付插件不兼容的原因，少传输了一个参数，也就是需要向收款渠道明确收款方式 。
解决办法就是在 易支付插件里面加上这个传输参数 /app/Payments/Epay.php
'type' => 'alipay' 或者 'type' => 'wxpay',
以上只是临时性的解决办法
彻底解决还需要再后端新增一个type的选项才行

![256209362-3e29da17-b90f-4cd2-a732-742253d417a9](https://github.com/user-attachments/assets/715d1c78-2faa-4352-a005-072cc3cf7040)

**Comment by wyx2685** [comment]
项目错误
另外本人不处理任何支付相关问题
