### ISSUE TITLE
请问xiao佬为啥将sing-box自定义dns的路径引用删除掉了

### ISSUE THREAD

**Issue by hexsen929** [wyx2685/V2bX#27]
之前使用sing-box可以通过引用 "DnsConfigPath": "/etc/V2bX/dns.json",修改一下json格式为sing-box的格式后能自定义dns，现在不行了。

**Comment by wyx2685** [comment]
挪到singbox自定义配置里面了
https://v2bx.v-50.me/v2bx/gong-neng-shuo-ming/singbox-nei-he-zi-ding-yi-pei-zhi-shuo-ming
