### ISSUE TITLE
一键脚本安装报错，检测 V2bX 版本失败

### ISSUE THREAD

**Issue by lengxii** [wyx2685/V2bX#29]
**描述该错误**
一键脚本安装报错

**复现**
这是我的系统信息
cat /proc/version
Linux version 6.1.0-25-cloud-amd64 (debian-kernel@lists.debian.org) (gcc-12 (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26)

**日志和错误**
`Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20230311).
ca-certificates set to manually installed.
wget is already the newest version (1.21.3-1+b2).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
检测 V2bX 版本失败，可能是超出 Github API 限制，请稍后再试，或手动指定 V2bX 版本安装
`

**Comment by vlesstop** [comment]
@lengxii bash install.sh v0.9.4-20240912

**Comment by lengxii** [comment]
> @lengxii bash install.sh v0.9.4-20240912

开始安装 V2bX v0.9.4-20240912
下载 V2bX v0.9.4-20240912 失败，请确保此版本存在

还是不行，我的机器是纯IPV6 VPS

`root@localhost:~# bash install.sh v0.9.4-20240912
架构: 64
开始安装
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
cron is already the newest version (3.0pl1-137).
curl is already the newest version (7.74.0-1.3+deb11u13).
socat is already the newest version (1.7.4.1-3).
tar is already the newest version (1.34+dfsg-1+deb11u1).
unzip is already the newest version (6.0-26+deb11u1).
wget is already the newest version (1.21-1+deb11u1).
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20210119).
wget is already the newest version (1.21-1+deb11u1).
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
开始安装 V2bX v0.9.4-20240912
下载 V2bX v0.9.4-20240912 失败，请确保此版本存在`

**Comment by vlesstop** [comment]
@lengxii 换下版本号啊，大哥。

**Comment by vlesstop** [comment]
@vlesstop bash install.sh v0.0.17 test-2024.10.06

**Comment by lengxii** [comment]
> @vlesstop bash install.sh v0.0.17 test-2024.10.06

这个版本号一样的报错

能自己手动上传包，再用脚本安装吗

**Comment by vlesstop** [comment]
@lengxii v0.0.17

**Comment by lengxii** [comment]
> @lengxii v0.0.17

root@localhost:~# bash install.sh v0.0.17
架构: 64
开始安装
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://deb.debian.org/debian bullseye-updates InRelease   
Hit:3 http://security.debian.org/debian-security bullseye-security InRelease
Reading package lists... Done                                   
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
cron is already the newest version (3.0pl1-137).
curl is already the newest version (7.74.0-1.3+deb11u13).
socat is already the newest version (1.7.4.1-3).
tar is already the newest version (1.34+dfsg-1+deb11u1).
unzip is already the newest version (6.0-26+deb11u1).
wget is already the newest version (1.21-1+deb11u1).
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20210119).
wget is already the newest version (1.21-1+deb11u1).
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
开始安装 V2bX v0.0.17
下载 V2bX v0.0.17 失败，请确保此版本存在

**Comment by vlesstop** [comment]
@lengxii 不知道了。

**Comment by wyx2685** [comment]
ipv6没有技术不要用，不行吗
