### ISSUE TITLE
help

### ISSUE THREAD

**Issue by KOTBCTAKAHE** [wyx2685/V2bX#37]
你好，我该怎么办？我制作了一个协议节点 "Splithttp"，但当我想用 cdn 连接它时，它会写入错误 404，它认为域名未知，当我删除 "Host "后，它开始工作，但我必须在订阅中手动写入 host，请告诉我该怎么办。

**Comment by wyx2685** [comment]
please don't use translate if you can't understand Chinese

send more details such as screen shot may help

**Comment by KOTBCTAKAHE** [comment]
Hello, what should I do? I created a protocol node "Splithttp", but when I try to connect it with a CDN, it gives a 404 error and thinks the domain is unknown. When I remove the "Host", it starts working, but I have to manually enter the host in the subscription. Please tell me what I should do.

how it should be:
![IMG_20241114_194348_006](https://github.com/user-attachments/assets/36f51a86-ab74-428c-b83e-28ed87e66ff7)

what it looks like with v2bx:
![IMG_20241114_194349_990](https://github.com/user-attachments/assets/b920ebf8-4e98-40db-8224-5a5e93af2f55)

**Comment by wyx2685** [comment]
just send all config and logs
we don't care what happened

**Comment by wyx2685** [comment]
seems you doesn't know anything of xray splithttp please stop use v2bx and learn xray document first
