### ISSUE TITLE
hy2 auth issue

### ISSUE THREAD

**Issue by cainia0** [wyx2685/V2bX#6]
在两台主机分别创建了两个hy2后端配置，可以正常使用，但是发现两条配置的密码相同
于是在 /etc/V2bX/hy2config.yaml 中添加了：

auth:
  type: password
  password: xxxxxxxx #设置认证密码

然而更新订阅后密码还是不变

创建过程：
V2bX 配置文件生成向导v  →  请选择节点核心类型  →  3. hysteria2

**Comment by wyx2685** [comment]
@cainia0 难道同用户密码能不相同吗

**Comment by cainia0** [comment]
> @cainia0 难道同用户密码能不相同吗

大佬这个我能理解，那可以麻烦大佬教我怎么改密码吗

**Comment by wyx2685** [comment]
密码是你面板给的uuid

**Comment by cainia0** [comment]
> 密码是你面板给的uuid

哦原来如此，原谅我是个菜鸟，哈哈，感谢大佬解惑
