### ISSUE TITLE
tls fingerprint issue

### ISSUE THREAD

**Issue by ippinger** [wyx2685/V2bX#7]
大佬您好，我注意到每次更新订阅的时候，vless节点中tls fingerprint的值都会改变，我十分想知道这个值是由后端V2bX决定的还是Xboard决定的，以及怎么修改这个值（这样我就不用在客户端里挨个设置了），期待能得到大佬的回复

**Comment by wyx2685** [comment]
@believerzhang 是你用的xboard决定的

**Comment by ippinger** [comment]
> @believerzhang 是你用的xboard决定的

可以拜托大佬教我怎么修改xboard的配置，使得vless的tls fingerprint值固定为某个值吗，我找了好久也没找到这个在哪里设置，问ai也没能解决

**Comment by wyx2685** [comment]
还是到xboard项目问吧
