### ISSUE TITLE
在线IP上报不正确

### ISSUE THREAD

**Issue by oQUoWuhf** [wyx2685/V2bX#8]
**描述该错误**
上报在线IP的方法，原本想定是发送 { UID1:["ip1","ip2"],UID2:["ip3","ip4"] } 这样的请求的，但实际在面板收到的请求中，UID始终是0，并且IP后面有下划线节点ID。 就像这样 {"0":["1.2.3.4_123"]}。（多用户和多IP同时在线的情况还未尝试）

由于我正在尝试给xboard增加记录在线IP的功能，所以希望能修复该问题。

**Comment by wyx2685** [comment]
@oQUoWuhf 自行对字符串按_进行分割处理吧
